version: '3'
services:
  web:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - ENVIRONMENT=development
      - PORT=8000
      - HOST=0.0.0.0
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
